name: Testing build on ubuntu-latest

on: [push, pull_request]

env:
  SKBUILD_CONFIGURE_OPTIONS: -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0'
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel build
          git submodule update --init --recursive
          pip install -r test_requirements.txt
          echo "SKBUILD_CONFIGURE_OPTIONS=${{ env.SKBUILD_CONFIGURE_OPTIONS }}" >> "$GITHUB_ENV"
          echo "SKBUILD_BUILD_OPTIONS=${{ env.SKBUILD_BUILD_OPTIONS }}" >> "$GITHUB_ENV"

      - name: make
        shell: bash
        run: |
          python -m build

      - name: install
        shell: bash
        run: |
          pip install dist/*.whl

      - name: make test
        shell: bash
        run: |
          python -m pytest -rsap python/tests

      - name: upload libcasm-global-ubuntu-latest-x86_64-dist
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: libcasm-global-ubuntu-latest-x86_64-dist
          path: dist
