name: Testing c++ only on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          git submodule update --init --recursive

      - name: configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=$CASM_PREFIX ..

      - name: make
        shell: bash
        run: |
          cd build
          make -j4 VERBOSE=1

      - name: make test
        shell: bash
        run: |
          cd build
          make -j4 test

      - name: upload test log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-log
          path: build/Testing/Temporary/LastTest.log
